export const data = [
  {
    id: 0,
    title: "Autumn Silence",
    url: "/autumn-silence",
    bgColor: { r: 255, g: 255, b: 255 },
    color: { r: 190, g: 142, b: 50 },
    topTitle: "Autumn",
    topGaps: [9, 3, 17, 2, 10, 4],
    botTitle: "Silence",
    botGaps: [12, 5, 5, 2, 15, 5, 6],
    infoLeft: {
      a: ["Completed", "March 2023"],
      b: ["Type", "Promotional"],
      c: ["Role", "Frontend Dev"],
      d: ["Client", "MGM Studios - Watson DC"],
    },
    infoRight: {
      top: "Explore the scenes of Beautiful mountains",
      bot: "and their serenity.",
    },
    images: [
      "/1/1.jpg",
      undefined,
      "/1/2.jpg",
      "/1/3.jpg",
      undefined,
      "/1/4.jpg",
      undefined,
      "/1/5.jpg",
      "/1/6.jpg",
      "/1/7.jpg",
    ],
  },
  {
    id: 1,
    title: "Desert Nights",
    url: "/desert-nights",
    bgColor: { r: 161, g: 99, b: 77 },
    color: { r: 237, g: 238, b: 240 },
    topTitle: "Desert",
    topGaps: [2, 13, 4, 2, 5, 1],
    botTitle: "Nights",
    botGaps: [8, 1, 6, 1, 25, 7, 0],
    infoLeft: {
      a: ["Completed", "March 2023"],
      b: ["Type", "Promotional"],
      c: ["Role", "Frontend Dev"],
      d: ["Client", "MGM Studios - Watson DC"],
    },
    infoRight: {
      top: "Explore the scenes of Beautiful mountains",
      bot: "and their serenity.",
    },
    images: [
      "/2/1.jpg",
      "/2/2.jpg",
      undefined,
      "/2/3.jpg",
      "/2/4.jpg",
      undefined,
      "/2/5.jpg",
      "/2/6.jpg",
      undefined,
      "/2/7.jpg",
    ],
  },
  {
    id: 2,
    title: "Urban",
    url: "/urban",
    bgColor: { r: 213, g: 213, b: 213 },
    color: { r: 42, g: 42, b: 42 },
    topTitle: "Urban",
    topGaps: [1, 13, 16, 17, 8, 1],
    botTitle: "",
    botGaps: [4, 1, 5, 2, 7, 1, 0],
    infoLeft: {
      a: ["Completed", "March 2023"],
      b: ["Type", "Promotional"],
      c: ["Role", "Frontend Dev"],
      d: ["Client", "MGM Studios - Watson DC"],
    },
    infoRight: {
      top: "Explore the scenes of Beautiful mountains",
      bot: "and their serenity.",
    },
    images: [
      "/3/1.jpg",
      "/3/2.jpg",
      undefined,
      "/3/3.jpg",
      undefined,
      "/3/4.jpg",
      "/3/5.jpg",
      undefined,
      "/3/6.jpg",
      "/3/7.jpg",
    ],
  },
  {
    id: 3,
    title: "Quiet Gaze",
    url: "/quiet-gaze",
    bgColor: { r: 120, g: 95, b: 78 },
    color: { r: 205, g: 185, b: 121 },
    topTitle: "Quiet",
    topGaps: [13, 3, 4, 26, 5, 1],
    botTitle: "Gaze",
    botGaps: [17, 1, 5, 22, 7, 1, 0],
    infoLeft: {
      a: ["Completed", "March 2023"],
      b: ["Type", "Promotional"],
      c: ["Role", "Frontend Dev"],
      d: ["Client", "MGM Studios - Watson DC"],
    },
    infoRight: {
      top: "Explore the scenes of Beautiful mountains",
      bot: "and their serenity.",
    },
    images: [
      "/4/1.jpg",
      undefined,
      "/4/2.jpg",
      "/4/3.jpg",
      undefined,
      "/4/4.jpg",
      "/4/5.jpg",
      "/4/6.jpg",
      undefined,
      "/4/7.jpg",
    ],
  },
  {
    id: 4,
    title: "Flowers&Flowers",
    url: "/flowers-and-flowers",
    bgColor: { r: 248, g: 248, b: 248 },
    color: { r: 211, g: 180, b: 38 },
    topTitle: "Flowers&",
    topGaps: [0, 3, 4, 2, 25, 1, 2, 5],
    botTitle: "Flowers",
    botGaps: [14, 1, 5, 22, 7, 1, 0],
    infoLeft: {
      a: ["Completed", "March 2023"],
      b: ["Type", "Promotional"],
      c: ["Role", "Frontend Dev"],
      d: ["Client", "MGM Studios - Watson DC"],
    },
    infoRight: {
      top: "Explore the scenes of Beautiful mountains",
      bot: "and their serenity.",
    },
    images: [
      undefined,
      "/5/1.jpg",
      "/5/2.jpg",
      "/5/3.jpg",
      undefined,
      "/5/4.jpg",
      "/5/5.jpg",
      undefined,
      "/5/6.jpg",
      "/5/7.jpg",
    ],
  },
  {
    id: 5,
    title: "DM",
    url: "/dm",
    bgColor: { r: 51, g: 51, b: 51 },
    color: { r: 207, g: 196, b: 190 },
    topTitle: "DM",
    topGaps: [22, 20],
    botTitle: "",
    botGaps: [0],
    infoLeft: {
      a: ["Completed", "March 2023"],
      b: ["Type", "Promotional"],
      c: ["Role", "Frontend Dev"],
      d: ["Client", "MGM Studios - Watson DC"],
    },
    infoRight: {
      top: "Explore the scenes of Beautiful mountains",
      bot: "and their serenity.",
    },
    images: [
      "/6/1.jpg",
      undefined,
      "/6/2.jpg",
      undefined,
      "/6/3.jpg",
      "/6/4.jpg",
      "/6/5.jpg",
      "/6/6.jpg",
      undefined,
      "/6/7.jpg",
    ],
  },
  {
    id: 6,
    title: "Pure Craft",
    url: "/pure-craft",
    bgColor: { r: 213, g: 226, b: 207 },
    color: { r: 221, g: 158, b: 124 },
    topTitle: "Pure",
    topGaps: [13, 33, 4, 7, 5, 1],
    botTitle: "Craft",
    botGaps: [5, 1, 5, 28, 7, 1, 0],
    infoLeft: {
      a: ["Completed", "March 2023"],
      b: ["Type", "Promotional"],
      c: ["Role", "Frontend Dev"],
      d: ["Client", "MGM Studios - Watson DC"],
    },
    infoRight: {
      top: "Explore the scenes of Beautiful mountains",
      bot: "and their serenity.",
    },
    images: [
      undefined,
      "/7/1.jpg",
      "/7/2.jpg",
      "/7/3.jpg",
      undefined,
      "/7/4.jpg",
      "/7/5.jpg",
      "/7/6.jpg",
      "/7/7.jpg",
      undefined,
    ],
  },
  {
    id: 7,
    title: "Dead Forest",
    url: "/dead-forest",
    bgColor: { r: 12, g: 24, b: 17 },
    color: { r: 215, g: 222, b: 236 },
    topTitle: "Dead",
    topGaps: [0, 15, 4, 10, 5, 1],
    botTitle: "Forest",
    botGaps: [12, 1, 5, 2, 17, 10, 0],
    infoLeft: {
      a: ["Completed", "March 2023"],
      b: ["Type", "Promotional"],
      c: ["Role", "Frontend Dev"],
      d: ["Client", "MGM Studios - Watson DC"],
    },
    infoRight: {
      top: "Explore the scenes of Beautiful mountains",
      bot: "and their serenity.",
    },
    images: [
      "/8/1.jpg",
      undefined,
      "/8/2.jpg",
      "/8/3.jpg",
      "/8/4.jpg",
      undefined,
      undefined,
      "/8/5.jpg",
      "/8/6.jpg",
      "/8/7.jpg",
    ],
  },
  {
    id: 8,
    title: "Morning Sun",
    url: "/morning-sun",
    bgColor: { r: 247, g: 234, b: 222 },
    color: { r: 139, g: 167, b: 168 },
    topTitle: "Morning",
    topGaps: [0, 3, 4, 8, 20, 1, 15],
    botTitle: "Sun",
    botGaps: [24, 1, 20, 2, 7, 1, 0],
    infoLeft: {
      a: ["Completed", "March 2023"],
      b: ["Type", "Promotional"],
      c: ["Role", "Frontend Dev"],
      d: ["Client", "MGM Studios - Watson DC"],
    },
    infoRight: {
      top: "Explore the scenes of Beautiful mountains",
      bot: "and their serenity.",
    },
    images: [
      "/9/1.jpg",
      undefined,
      "/9/2.jpg",
      "/9/3.jpg",
      undefined,
      "/9/4.jpg",
      undefined,
      "/9/5.jpg",
      "/9/6.jpg",
      "/9/7.jpg",
    ],
  },
  {
    id: 9,
    title: "Stool",
    url: "/stool",
    bgColor: { r: 222, g: 222, b: 222 },
    color: { r: 255, g: 142, b: 50 },
    topTitle: "Stool",
    topGaps: [0, 3, 24, 12, 15, 1],
    botTitle: "",
    botGaps: [4, 1, 5, 2, 7, 1, 0],
    infoLeft: {
      a: ["Completed", "March 2023"],
      b: ["Type", "Promotional"],
      c: ["Role", "Frontend Dev"],
      d: ["Client", "MGM Studios - Watson DC"],
    },
    infoRight: {
      top: "Explore the scenes of Beautiful mountains",
      bot: "and their serenity.",
    },
    images: [
      "/10/1.jpg",
      undefined,
      "/10/2.jpg",
      undefined,
      "/10/3.jpg",
      "/10/4.jpg",
      "/10/5.jpg",
      undefined,
      "/10/6.jpg",
      "/10/7.jpg",
    ],
  },

  {
    id: 10,
    title: "Foreign Lakes",
    url: "/foreign-lakes",
    bgColor: { r: 219, g: 226, b: 234 },
    color: { r: 192, g: 112, b: 5 },
    topTitle: "Foreign",
    topGaps: [10, 3, 4, 12, 5, 9, 2],
    botTitle: "Lakes",
    botGaps: [4, 11, 5, 2, 25, 21, 0],
    infoLeft: {
      a: ["Completed", "March 2023"],
      b: ["Type", "Promotional"],
      c: ["Role", "Frontend Dev"],
      d: ["Client", "MGM Studios - Watson DC"],
    },
    infoRight: {
      top: "Explore the scenes of Beautiful mountains",
      bot: "and their serenity.",
    },
    images: [
      "/11/1.jpg",
      undefined,
      "/11/2.jpg",
      undefined,
      "/11/3.jpg",
      "/11/4.jpg",
      "/11/5.jpg",
      "/11/6.jpg",
      undefined,
      "/11/7.jpg",
    ],
  },
  {
    id: 11,
    title: "Italian Views",
    url: "/italian-views",
    bgColor: { r: 207, g: 217, b: 229 },
    color: { r: 201, g: 49, b: 20 },
    topTitle: "Italian",
    topGaps: [5, 13, 14, 12, 5, 1, 10],
    botTitle: "Views",
    botGaps: [14, 5, 30, 2, 7, 1, 0],
    infoLeft: {
      a: ["Completed", "March 2023"],
      b: ["Type", "Promotional"],
      c: ["Role", "Frontend Dev"],
      d: ["Client", "MGM Studios - Watson DC"],
    },
    infoRight: {
      top: "Explore the scenes of Beautiful mountains",
      bot: "and their serenity.",
    },
    images: [
      undefined,
      "/12/1.jpg",
      "/12/2.jpg",
      "/12/3.jpg",
      "/12/4.jpg",
      undefined,
      "/12/5.jpg",
      "/12/6.jpg",
      "/12/7.jpg",
      undefined,
    ],
  },

  {
    id: 12,
    title: "Warm Beach",
    url: "/warm-beach",
    bgColor: { r: 216, g: 239, b: 255 },
    color: { r: 216, g: 165, b: 52 },
    topTitle: "Warm",
    topGaps: [10, 3, 24, 12, 5, 1],
    botTitle: "Beach",
    botGaps: [15, 3, 1, 27, 7, 1, 0],
    infoLeft: {
      a: ["Completed", "March 2023"],
      b: ["Type", "Promotional"],
      c: ["Role", "Frontend Dev"],
      d: ["Client", "MGM Studios - Watson DC"],
    },
    infoRight: {
      top: "Explore the scenes of Beautiful mountains",
      bot: "and their serenity.",
    },
    images: [
      "/13/1.jpg",
      "/13/2.jpg",
      undefined,
      "/13/3.jpg",
      "/13/4.jpg",
      undefined,
      "/13/5.jpg",
      undefined,
      "/13/6.jpg",
      "/13/7.jpg",
    ],
  },
  {
    id: 13,
    title: "Film History",
    url: "/film-history",
    bgColor: { r: 206, g: 206, b: 217 },
    color: { r: 28, g: 28, b: 26 },
    topTitle: "Film",
    topGaps: [0, 3, 24, 22, 5, 1],
    botTitle: "History",
    botGaps: [14, 1, 7, 20, 5, 1, 0],
    infoLeft: {
      a: ["Completed", "March 2023"],
      b: ["Type", "Promotional"],
      c: ["Role", "Frontend Dev"],
      d: ["Client", "MGM Studios - Watson DC"],
    },
    infoRight: {
      top: "Explore the scenes of Beautiful mountains",
      bot: "and their serenity.",
    },
    images: [
      "/14/1.jpg",
      "/14/2.jpg",
      undefined,
      "/14/3.jpg",
      "/14/4.jpg",
      undefined,
      "/14/5.jpg",
      "/14/6.jpg",
      undefined,
      "/14/7.jpg",
    ],
  },
  {
    id: 14,
    title: "Castlevania",
    url: "/castlevania",
    bgColor: { r: 199, g: 195, b: 184 },
    color: { r: 189, g: 96, b: 74 },
    topTitle: "Castlevania",
    topGaps: [0, 6, 4, 2, 5, 1, 5, 1, 9, 2, 1, 0, 1],
    botTitle: "",
    botGaps: [4, 1, 5, 2, 7, 1, 0],
    infoLeft: {
      a: ["Completed", "March 2023"],
      b: ["Type", "Promotional"],
      c: ["Role", "Frontend Dev"],
      d: ["Client", "MGM Studios - Watson DC"],
    },
    infoRight: {
      top: "Explore the scenes of Beautiful mountains",
      bot: "and their serenity.",
    },
    images: [
      undefined,
      "/15/1.jpg",
      undefined,
      "/15/2.jpg",
      "/15/3.jpg",
      "/15/4.jpg",
      "/15/5.jpg",
      "/15/6.jpg",
      undefined,
      "/15/7.jpg",
    ],
  },
  {
    id: 15,
    title: "Carribean Expo",
    url: "/carribean-expo",
    bgColor: { r: 128, g: 176, b: 211 },
    color: { r: 211, g: 33, b: 0 },
    topTitle: "Carribean",
    topGaps: [12, 3, 7, 2, 10, 4, 1, 5, 2],
    botTitle: "Expo",
    botGaps: [15, 5, 25, 2, 15, 5, 6],
    infoLeft: {
      a: ["Completed", "March 2023"],
      b: ["Type", "Promotional"],
      c: ["Role", "Frontend Dev"],
      d: ["Client", "MGM Studios - Watson DC"],
    },
    infoRight: {
      top: "Explore the scenes of Beautiful mountains",
      bot: "and their serenity.",
    },
    images: [
      undefined,
      "/16/1.jpg",
      "/16/2.jpg",
      undefined,
      "/16/3.jpg",
      "/16/4.jpg",
      "/16/5.jpg",
      "/16/6.jpg",
      "/16/7.jpg",
      undefined,
    ],
  },
  {
    id: 16,
    title: "Rock&Stone",
    url: "/rock-and-stone",
    bgColor: { r: 221, g: 221, b: 221 },
    color: { r: 128, g: 176, b: 0 },
    topTitle: "Rock&",
    topGaps: [2, 13, 4, 2, 5, 1],
    botTitle: "Stone",
    botGaps: [8, 1, 6, 1, 25, 7, 0],
    infoLeft: {
      a: ["Completed", "March 2023"],
      b: ["Type", "Promotional"],
      c: ["Role", "Frontend Dev"],
      d: ["Client", "MGM Studios - Watson DC"],
    },
    infoRight: {
      top: "Explore the scenes of Beautiful mountains",
      bot: "and their serenity.",
    },
    images: [
      "/17/1.jpg",
      undefined,
      "/17/2.jpg",
      "/17/3.jpg",
      undefined,
      "/17/4.jpg",
      undefined,
      "/17/5.jpg",
      "/17/6.jpg",
      "/17/7.jpg",
    ],
  },
  {
    id: 17,
    title: "Highway Chill",
    url: "/highway-chill",
    bgColor: { r: 154, g: 153, b: 152 },
    color: { r: 255, g: 182, b: 40 },
    topTitle: "Highway",
    topGaps: [1, 13, 12, 17, 8, 1, 1],
    botTitle: "Chill",
    botGaps: [4, 1, 5, 24, 7, 1, 0],
    infoLeft: {
      a: ["Completed", "March 2023"],
      b: ["Type", "Promotional"],
      c: ["Role", "Frontend Dev"],
      d: ["Client", "MGM Studios - Watson DC"],
    },
    infoRight: {
      top: "Explore the scenes of Beautiful mountains",
      bot: "and their serenity.",
    },
    images: [
      "/18/1.jpg",
      undefined,
      "/18/2.jpg",
      undefined,
      "/18/3.jpg",
      "/18/4.jpg",
      "/18/5.jpg",
      undefined,
      "/18/6.jpg",
      "/18/7.jpg",
    ],
  },
  {
    id: 18,
    title: "African Safari",
    url: "/african-safari",
    bgColor: { r: 156, g: 168, b: 182 },
    color: { r: 41, g: 32, b: 26 },
    topTitle: "African",
    topGaps: [13, 3, 4, 26, 5, 1, 4],
    botTitle: "Safari",
    botGaps: [17, 1, 5, 22, 7, 1, 0],
    infoLeft: {
      a: ["Completed", "March 2023"],
      b: ["Type", "Promotional"],
      c: ["Role", "Frontend Dev"],
      d: ["Client", "MGM Studios - Watson DC"],
    },
    infoRight: {
      top: "Explore the scenes of Beautiful mountains",
      bot: "and their serenity.",
    },
    images: [
      "/19/1.jpg",
      undefined,
      "/19/2.jpg",
      "/19/3.jpg",
      "/19/4.jpg",
      undefined,
      "/19/5.jpg",
      "/19/6.jpg",
      undefined,
      "/19/7.jpg",
    ],
  },

  {
    id: 19,
    title: "Magic Hour",
    url: "/magic-hour",
    bgColor: { r: 144, g: 151, b: 152 },
    color: { r: 205, g: 197, b: 187 },
    topTitle: "Magic",
    topGaps: [0, 3, 4, 2, 25, 1, 2, 5],
    botTitle: "Hour",
    botGaps: [14, 1, 5, 22, 7, 1, 0],
    infoLeft: {
      a: ["Completed", "March 2023"],
      b: ["Type", "Promotional"],
      c: ["Role", "Frontend Dev"],
      d: ["Client", "MGM Studios - Watson DC"],
    },
    infoRight: {
      top: "Explore the scenes of Beautiful mountains",
      bot: "and their serenity.",
    },
    images: [
      "/20/1.jpg",
      undefined,
      "/20/2.jpg",
      undefined,
      "/20/3.jpg",
      "/20/4.jpg",
      "/20/5.jpg",
      "/20/6.jpg",
      undefined,
      "/20/7.jpg",
    ],
  },
  {
    id: 20,
    title: "Norway Train",
    url: "/norway-train",
    bgColor: { r: 183, g: 202, b: 203 },
    color: { r: 176, g: 65, b: 19 },
    topTitle: "Norway",
    topGaps: [13, 3, 28, 7, 5, 1],
    botTitle: "Train",
    botGaps: [5, 1, 5, 28, 7, 1, 0],
    infoLeft: {
      a: ["Completed", "March 2023"],
      b: ["Type", "Promotional"],
      c: ["Role", "Frontend Dev"],
      d: ["Client", "MGM Studios - Watson DC"],
    },
    infoRight: {
      top: "Explore the scenes of Beautiful mountains",
      bot: "and their serenity.",
    },
    images: [
      "/21/1.jpg",
      undefined,
      "/21/2.jpg",
      "/21/3.jpg",
      "/21/4.jpg",
      "/21/5.jpg",
      undefined,
      "/21/6.jpg",
      undefined,
      "/21/7.jpg",
    ],
  },
  {
    id: 21,
    title: "Blossom",
    url: "/blossom",
    bgColor: { r: 65, g: 51, b: 40 },
    color: { r: 166, g: 189, b: 88 },
    topTitle: "Blossom",
    topGaps: [0, 15, 4, 10, 5, 1, 6],
    botTitle: "",
    botGaps: [12, 1, 5, 2, 17, 10, 0],
    infoLeft: {
      a: ["Completed", "March 2023"],
      b: ["Type", "Promotional"],
      c: ["Role", "Frontend Dev"],
      d: ["Client", "MGM Studios - Watson DC"],
    },
    infoRight: {
      top: "Explore the scenes of Beautiful mountains",
      bot: "and their serenity.",
    },
    images: [
      "/22/1.jpg",
      undefined,
      "/22/2.jpg",
      "/22/3.jpg",
      "/22/4.jpg",
      "/22/5.jpg",
      undefined,
      "/22/6.jpg",
      undefined,
      "/22/7.jpg",
    ],
  },
  {
    id: 22,
    title: "Vietam Today",
    url: "/vietnam-today",
    bgColor: { r: 241, g: 229, b: 171 },
    color: { r: 86, g: 113, b: 81 },
    topTitle: "Vietam",
    topGaps: [0, 3, 4, 8, 20, 1, 15],
    botTitle: "Today",
    botGaps: [24, 1, 20, 2, 7, 1, 0],
    infoLeft: {
      a: ["Completed", "March 2023"],
      b: ["Type", "Promotional"],
      c: ["Role", "Frontend Dev"],
      d: ["Client", "MGM Studios - Watson DC"],
    },
    infoRight: {
      top: "Explore the scenes of Beautiful mountains",
      bot: "and their serenity.",
    },
    images: [
      undefined,
      "/23/1.jpg",
      "/23/2.jpg",
      "/23/3.jpg",
      undefined,
      "/23/4.jpg",
      "/23/5.jpg",
      "/23/6.jpg",
      "/23/7.jpg",
      undefined,
    ],
  },
  {
    id: 23,
    title: "MAGA MAGA",
    url: "/maga-maga",
    bgColor: { r: 68, g: 64, b: 53 },
    color: { r: 225, g: 211, b: 190 },
    topTitle: "MAGA",
    topGaps: [0, 3, 24, 12, 15, 1],
    botTitle: "MAGA",
    botGaps: [14, 21, 15, 2, 7, 11, 0],
    infoLeft: {
      a: ["Completed", "March 2023"],
      b: ["Type", "Promotional"],
      c: ["Role", "Frontend Dev"],
      d: ["Client", "MGM Studios - Watson DC"],
    },
    infoRight: {
      top: "Explore the scenes of Beautiful mountains",
      bot: "and their serenity.",
    },
    images: [
      "/24/1.jpg",
      "/24/2.jpg",
      undefined,
      "/24/3.jpg",
      "/24/4.jpg",
      undefined,
      "/24/5.jpg",
      "/24/6.jpg",
      undefined,
      "/24/7.jpg",
    ],
  },
  {
    id: 24,
    title: "Civil Peace",
    url: "/civil-peace",
    bgColor: { r: 225, g: 184, b: 163 },
    color: { r: 250, g: 254, b: 255 },
    topTitle: "Civil",
    topGaps: [10, 3, 4, 12, 5, 9, 2],
    botTitle: "Peace",
    botGaps: [4, 11, 25, 2, 25, 21, 0],
    infoLeft: {
      a: ["Completed", "March 2023"],
      b: ["Type", "Promotional"],
      c: ["Role", "Frontend Dev"],
      d: ["Client", "MGM Studios - Watson DC"],
    },
    infoRight: {
      top: "Explore the scenes of Beautiful mountains",
      bot: "and their serenity.",
    },
    images: [
      "/25/1.jpg",
      "/25/2.jpg",
      "/25/3.jpg",
      undefined,
      "/25/4.jpg",
      undefined,
      "/25/5.jpg",
      "/25/6.jpg",
      undefined,
      "/25/7.jpg",
    ],
  },
  {
    id: 25,
    title: "Quiet Space",
    url: "/quiet-space",
    bgColor: { r: 17, g: 11, b: 7 },
    color: { r: 223, g: 150, b: 63 },
    topTitle: "Quiet",
    topGaps: [5, 13, 14, 12, 5, 1, 10],
    botTitle: "Space",
    botGaps: [14, 5, 30, 2, 7, 1, 0],
    infoLeft: {
      a: ["Completed", "March 2023"],
      b: ["Type", "Promotional"],
      c: ["Role", "Frontend Dev"],
      d: ["Client", "MGM Studios - Watson DC"],
    },
    infoRight: {
      top: "Explore the scenes of Beautiful mountains",
      bot: "and their serenity.",
    },
    images: [
      "/26/1.jpg",
      undefined,
      "/26/2.jpg",
      "/26/3.jpg",
      undefined,
      "/26/4.jpg",
      undefined,
      "/26/5.jpg",
      "/26/6.jpg",
      "/26/7.jpg",
    ],
  },
  {
    id: 26,
    title: "Solid Rock",
    url: "/solid-rock",
    bgColor: { r: 253, g: 253, b: 253 },
    color: { r: 149, g: 59, b: 31 },
    topTitle: "Solid",
    topGaps: [10, 3, 24, 12, 5, 1],
    botTitle: "Rock",
    botGaps: [15, 3, 1, 27, 7, 1, 0],
    infoLeft: {
      a: ["Completed", "March 2023"],
      b: ["Type", "Promotional"],
      c: ["Role", "Frontend Dev"],
      d: ["Client", "MGM Studios - Watson DC"],
    },
    infoRight: {
      top: "Explore the scenes of Beautiful mountains",
      bot: "and their serenity.",
    },
    images: [
      "/27/1.jpg",
      undefined,
      "/27/2.jpg",
      "/27/3.jpg",
      "/27/4.jpg",
      undefined,
      "/27/5.jpg",
      "/27/6.jpg",
      undefined,
      "/27/7.jpg",
    ],
  },
  {
    id: 27,
    title: "Grand Hotel",
    url: "/grand-hotel",
    bgColor: { r: 51, g: 51, b: 51 },
    color: { r: 255, g: 255, b: 255 },
    topTitle: "Grand",
    topGaps: [0, 3, 24, 22, 5, 1],
    botTitle: "Hotel",
    botGaps: [14, 1, 7, 20, 5, 1, 0],
    infoLeft: {
      a: ["Completed", "March 2023"],
      b: ["Type", "Promotional"],
      c: ["Role", "Frontend Dev"],
      d: ["Client", "MGM Studios - Watson DC"],
    },
    infoRight: {
      top: "Explore the scenes of Beautiful mountains",
      bot: "and their serenity.",
    },
    images: [
      "/28/1.jpg",
      undefined,
      "/28/2.jpg",
      undefined,
      "/28/3.jpg",
      "/28/4.jpg",
      "/28/5.jpg",
      undefined,
      "/28/6.jpg",
      "/28/7.jpg",
    ],
  },
  {
    id: 28,
    title: "Spring Tulip",
    url: "/spring-tulip",
    bgColor: { r: 228, g: 212, b: 187 },
    color: { r: 81, g: 120, b: 221 },
    topTitle: "Spring",
    topGaps: [0, 6, 14, 2, 5, 11, 5, 1, 9, 2, 1, 0, 1],
    botTitle: "Tulip",
    botGaps: [4, 1, 5, 12, 17, 5, 0],
    infoLeft: {
      a: ["Completed", "March 2023"],
      b: ["Type", "Promotional"],
      c: ["Role", "Frontend Dev"],
      d: ["Client", "MGM Studios - Watson DC"],
    },
    infoRight: {
      top: "Explore the scenes of Beautiful mountains",
      bot: "and their serenity.",
    },
    images: [
      "/29/1.jpg",
      undefined,
      "/29/2.jpg",
      "/29/3.jpg",
      "/29/4.jpg",
      undefined,
      "/29/5.jpg",
      "/29/6.jpg",
      undefined,
      "/29/7.jpg",
    ],
  },
  {
    id: 29,
    title: "Earth Roots",
    url: "/earth-roots",
    bgColor: { r: 196, g: 199, b: 205 },
    color: { r: 117, g: 79, b: 57 },
    topTitle: "Earth",
    topGaps: [12, 3, 7, 2, 10, 4, 1, 5, 2],
    botTitle: "Roots",
    botGaps: [15, 5, 25, 2, 15, 5, 6],
    infoLeft: {
      a: ["Completed", "March 2023"],
      b: ["Type", "Promotional"],
      c: ["Role", "Frontend Dev"],
      d: ["Client", "MGM Studios - Watson DC"],
    },
    infoRight: {
      top: "Explore the scenes of Beautiful mountains",
      bot: "and their serenity.",
    },
    images: [
      "/30/1.jpg",
      undefined,
      "/30/2.jpg",
      "/30/3.jpg",
      "/30/4.jpg",
      undefined,
      "/30/5.jpg",
      "/30/6.jpg",
      undefined,
      "/30/7.jpg",
    ],
  },
];
