export const data = [
  {
    id: 0,
    title: "first",
    bgColor: { r: 51, g: 51, b: 51 },
    color: { r: 255, g: 255, b: 255 },
    topTitle: "Autumn",
    botTitle: "Silence",
    infoLeft: {
      a: ["Completed", "March 2023"],
      b: ["Type", "Promotional"],
      c: ["Role", "Frontend Dev"],
      d: ["Client", "MGM Studios - Watson DC"],
    },
    infoRight: {
      top: "Explore the scenes of Beautiful mountains",
      bot: "and their serenity.",
    },
    images: [
      "./images/1.jpg",
      undefined,
      "./images/2.jpg",
      "./images/3.jpg",
      undefined,
      "./images/4.jpg",
      undefined,
      "./images/5.jpg",
      "./images/6.jpg",
      "./images/7.jpg",
    ],
  },
  {
    id: 1,
    title: "first",
    bgColor: { r: 161, g: 99, b: 77 },
    color: { r: 237, g: 238, b: 240 },
    topTitle: "Autumn",
    botTitle: "Silence",
    infoLeft: {
      a: ["Completed", "March 2023"],
      b: ["Type", "Promotional"],
      c: ["Role", "Frontend Dev"],
      d: ["Client", "MGM Studios - Watson DC"],
    },
    infoRight: {
      top: "Explore the scenes of Beautiful mountains",
      bot: "and their serenity.",
    },
    images: [
      "./images/1.jpg",
      "./images/2.jpg",
      undefined,
      "./images/3.jpg",
      "./images/4.jpg",
      undefined,
      "./images/5.jpg",
      "./images/6.jpg",
      undefined,
      "./images/7.jpg",
    ],
  },
  {
    id: 2,
    title: "first",
    bgColor: { r: 213, g: 213, b: 213 },
    color: { r: 42, g: 42, b: 42 },
    topTitle: "Autumn",
    botTitle: "Silence",
    infoLeft: {
      a: ["Completed", "March 2023"],
      b: ["Type", "Promotional"],
      c: ["Role", "Frontend Dev"],
      d: ["Client", "MGM Studios - Watson DC"],
    },
    infoRight: {
      top: "Explore the scenes of Beautiful mountains",
      bot: "and their serenity.",
    },
    images: [
      "./images/1.jpg",
      "./images/2.jpg",
      undefined,
      "./images/3.jpg",
      undefined,
      "./images/4.jpg",
      "./images/5.jpg",
      undefined,
      "./images/6.jpg",
      "./images/7.jpg",
    ],
  },
  {
    id: 3,
    title: "first",
    bgColor: { r: 120, g: 95, b: 78 },
    color: { r: 205, g: 185, b: 121 },
    topTitle: "Autumn",
    botTitle: "Silence",
    infoLeft: {
      a: ["Completed", "March 2023"],
      b: ["Type", "Promotional"],
      c: ["Role", "Frontend Dev"],
      d: ["Client", "MGM Studios - Watson DC"],
    },
    infoRight: {
      top: "Explore the scenes of Beautiful mountains",
      bot: "and their serenity.",
    },
    images: [
      "./images/1.jpg",
      undefined,
      "./images/2.jpg",
      "./images/3.jpg",
      undefined,
      "./images/4.jpg",
      "./images/5.jpg",
      "./images/6.jpg",
      undefined,
      "./images/7.jpg",
    ],
  },
  {
    id: 4,
    title: "first",
    bgColor: { r: 248, g: 248, b: 248 },
    color: { r: 211, g: 180, b: 38 },
    topTitle: "Autumn",
    botTitle: "Silence",
    infoLeft: {
      a: ["Completed", "March 2023"],
      b: ["Type", "Promotional"],
      c: ["Role", "Frontend Dev"],
      d: ["Client", "MGM Studios - Watson DC"],
    },
    infoRight: {
      top: "Explore the scenes of Beautiful mountains",
      bot: "and their serenity.",
    },
    images: [
      undefined,
      "./images/1.jpg",
      "./images/2.jpg",
      "./images/3.jpg",
      undefined,
      "./images/4.jpg",
      "./images/5.jpg",
      undefined,
      "./images/6.jpg",
      "./images/7.jpg",
    ],
  },
  {
    id: 5,
    title: "first",
    bgColor: { r: 51, g: 51, b: 51 },
    color: { r: 207, g: 196, b: 190 },
    topTitle: "Autumn",
    botTitle: "Silence",
    infoLeft: {
      a: ["Completed", "March 2023"],
      b: ["Type", "Promotional"],
      c: ["Role", "Frontend Dev"],
      d: ["Client", "MGM Studios - Watson DC"],
    },
    infoRight: {
      top: "Explore the scenes of Beautiful mountains",
      bot: "and their serenity.",
    },
    images: [
      "./images/1.jpg",
      undefined,
      "./images/2.jpg",
      undefined,
      "./images/3.jpg",
      "./images/4.jpg",
      "./images/5.jpg",
      "./images/6.jpg",
      undefined,
      "./images/7.jpg",
    ],
  },
  {
    id: 6,
    title: "first",
    bgColor: { r: 213, g: 226, b: 207 },
    color: { r: 221, g: 158, b: 124 },
    topTitle: "Autumn",
    botTitle: "Silence",
    infoLeft: {
      a: ["Completed", "March 2023"],
      b: ["Type", "Promotional"],
      c: ["Role", "Frontend Dev"],
      d: ["Client", "MGM Studios - Watson DC"],
    },
    infoRight: {
      top: "Explore the scenes of Beautiful mountains",
      bot: "and their serenity.",
    },
    images: [
      undefined,
      "./images/1.jpg",
      "./images/2.jpg",
      "./images/3.jpg",
      undefined,
      "./images/4.jpg",
      "./images/5.jpg",
      "./images/6.jpg",
      "./images/7.jpg",
      undefined,
    ],
  },
  {
    id: 7,
    title: "first",
    bgColor: { r: 12, g: 24, b: 17 },
    color: { r: 215, g: 222, b: 236 },
    topTitle: "Autumn",
    botTitle: "Silence",
    infoLeft: {
      a: ["Completed", "March 2023"],
      b: ["Type", "Promotional"],
      c: ["Role", "Frontend Dev"],
      d: ["Client", "MGM Studios - Watson DC"],
    },
    infoRight: {
      top: "Explore the scenes of Beautiful mountains",
      bot: "and their serenity.",
    },
    images: [
      "./images/1.jpg",
      undefined,
      "./images/2.jpg",
      "./images/3.jpg",
      "./images/4.jpg",
      undefined,
      undefined,
      "./images/5.jpg",
      "./images/6.jpg",
      "./images/7.jpg",
    ],
  },
  {
    id: 8,
    title: "first",
    bgColor: { r: 247, g: 234, b: 222 },
    color: { r: 139, g: 167, b: 168 },
    topTitle: "Autumn",
    botTitle: "Silence",
    infoLeft: {
      a: ["Completed", "March 2023"],
      b: ["Type", "Promotional"],
      c: ["Role", "Frontend Dev"],
      d: ["Client", "MGM Studios - Watson DC"],
    },
    infoRight: {
      top: "Explore the scenes of Beautiful mountains",
      bot: "and their serenity.",
    },
    images: [
      "./images/1.jpg",
      undefined,
      "./images/2.jpg",
      "./images/3.jpg",
      undefined,
      "./images/4.jpg",
      undefined,
      "./images/5.jpg",
      "./images/6.jpg",
      "./images/7.jpg",
    ],
  },
  {
    id: 9,
    title: "first",
    bgColor: { r: 222, g: 222, b: 222 },
    color: { r: 255, g: 142, b: 50 },
    topTitle: "Autumn",
    botTitle: "Silence",
    infoLeft: {
      a: ["Completed", "March 2023"],
      b: ["Type", "Promotional"],
      c: ["Role", "Frontend Dev"],
      d: ["Client", "MGM Studios - Watson DC"],
    },
    infoRight: {
      top: "Explore the scenes of Beautiful mountains",
      bot: "and their serenity.",
    },
    images: [
      "./images/1.jpg",
      undefined,
      "./images/2.jpg",
      undefined,
      "./images/3.jpg",
      "./images/4.jpg",
      "./images/5.jpg",
      undefined,
      "./images/6.jpg",
      "./images/7.jpg",
    ],
  },

  {
    id: 10,
    title: "first",
    bgColor: { r: 219, g: 226, b: 234 },
    color: { r: 192, g: 112, b: 5 },
    topTitle: "Autumn",
    botTitle: "Silence",
    infoLeft: {
      a: ["Completed", "March 2023"],
      b: ["Type", "Promotional"],
      c: ["Role", "Frontend Dev"],
      d: ["Client", "MGM Studios - Watson DC"],
    },
    infoRight: {
      top: "Explore the scenes of Beautiful mountains",
      bot: "and their serenity.",
    },
    images: [
      "./images/1.jpg",
      undefined,
      "./images/2.jpg",
      undefined,
      "./images/3.jpg",
      "./images/4.jpg",
      "./images/5.jpg",
      "./images/6.jpg",
      undefined,
      "./images/7.jpg",
    ],
  },
  {
    id: 11,
    title: "first",
    bgColor: { r: 207, g: 217, b: 229 },
    color: { r: 201, g: 49, b: 20 },
    topTitle: "Autumn",
    botTitle: "Silence",
    infoLeft: {
      a: ["Completed", "March 2023"],
      b: ["Type", "Promotional"],
      c: ["Role", "Frontend Dev"],
      d: ["Client", "MGM Studios - Watson DC"],
    },
    infoRight: {
      top: "Explore the scenes of Beautiful mountains",
      bot: "and their serenity.",
    },
    images: [
      undefined,
      "./images/1.jpg",
      "./images/2.jpg",
      "./images/3.jpg",
      "./images/4.jpg",
      undefined,
      "./images/5.jpg",
      "./images/6.jpg",
      "./images/7.jpg",
      undefined,
    ],
  },

  {
    id: 12,
    title: "first",
    bgColor: { r: 216, g: 239, b: 255 },
    color: { r: 216, g: 165, b: 52 },
    topTitle: "Autumn",
    botTitle: "Silence",
    infoLeft: {
      a: ["Completed", "March 2023"],
      b: ["Type", "Promotional"],
      c: ["Role", "Frontend Dev"],
      d: ["Client", "MGM Studios - Watson DC"],
    },
    infoRight: {
      top: "Explore the scenes of Beautiful mountains",
      bot: "and their serenity.",
    },
    images: [
      "./images/1.jpg",
      "./images/2.jpg",
      undefined,
      "./images/3.jpg",
      "./images/4.jpg",
      undefined,
      "./images/5.jpg",
      undefined,
      "./images/6.jpg",
      "./images/7.jpg",
    ],
  },
  {
    id: 13,
    title: "first",
    bgColor: { r: 206, g: 206, b: 217 },
    color: { r: 28, g: 28, b: 26 },
    topTitle: "Autumn",
    botTitle: "Silence",
    infoLeft: {
      a: ["Completed", "March 2023"],
      b: ["Type", "Promotional"],
      c: ["Role", "Frontend Dev"],
      d: ["Client", "MGM Studios - Watson DC"],
    },
    infoRight: {
      top: "Explore the scenes of Beautiful mountains",
      bot: "and their serenity.",
    },
    images: [
      "./images/1.jpg",
      "./images/2.jpg",
      undefined,
      "./images/3.jpg",
      "./images/4.jpg",
      undefined,
      "./images/5.jpg",
      "./images/6.jpg",
      undefined,
      "./images/7.jpg",
    ],
  },
  {
    id: 14,
    title: "first",
    bgColor: { r: 199, g: 195, b: 184 },
    color: { r: 189, g: 96, b: 74 },
    topTitle: "Autumn",
    botTitle: "Silence",
    infoLeft: {
      a: ["Completed", "March 2023"],
      b: ["Type", "Promotional"],
      c: ["Role", "Frontend Dev"],
      d: ["Client", "MGM Studios - Watson DC"],
    },
    infoRight: {
      top: "Explore the scenes of Beautiful mountains",
      bot: "and their serenity.",
    },
    images: [
      undefined,
      "./images/1.jpg",
      undefined,
      "./images/2.jpg",
      "./images/3.jpg",
      "./images/4.jpg",
      "./images/5.jpg",
      "./images/6.jpg",
      undefined,
      "./images/7.jpg",
    ],
  },
  {
    id: 15,
    title: "first",
    bgColor: { r: 128, g: 176, b: 211 },
    color: { r: 211, g: 33, b: 0 },
    topTitle: "Autumn",
    botTitle: "Silence",
    infoLeft: {
      a: ["Completed", "March 2023"],
      b: ["Type", "Promotional"],
      c: ["Role", "Frontend Dev"],
      d: ["Client", "MGM Studios - Watson DC"],
    },
    infoRight: {
      top: "Explore the scenes of Beautiful mountains",
      bot: "and their serenity.",
    },
    images: [
      undefined,
      "./images/1.jpg",
      "./images/2.jpg",
      undefined,
      "./images/3.jpg",
      "./images/4.jpg",
      "./images/5.jpg",
      "./images/6.jpg",
      "./images/7.jpg",
      undefined,
    ],
  },
  {
    id: 16,
    title: "first",
    bgColor: { r: 221, g: 221, b: 221 },
    color: { r: 128, g: 176, b: 0 },
    topTitle: "Autumn",
    botTitle: "Silence",
    infoLeft: {
      a: ["Completed", "March 2023"],
      b: ["Type", "Promotional"],
      c: ["Role", "Frontend Dev"],
      d: ["Client", "MGM Studios - Watson DC"],
    },
    infoRight: {
      top: "Explore the scenes of Beautiful mountains",
      bot: "and their serenity.",
    },
    images: [
      "./images/1.jpg",
      undefined,
      "./images/2.jpg",
      "./images/3.jpg",
      undefined,
      "./images/4.jpg",
      undefined,
      "./images/5.jpg",
      "./images/6.jpg",
      "./images/7.jpg",
    ],
  },
  {
    id: 17,
    title: "first",
    bgColor: { r: 154, g: 153, b: 152 },
    color: { r: 255, g: 182, b: 40 },
    topTitle: "Autumn",
    botTitle: "Silence",
    infoLeft: {
      a: ["Completed", "March 2023"],
      b: ["Type", "Promotional"],
      c: ["Role", "Frontend Dev"],
      d: ["Client", "MGM Studios - Watson DC"],
    },
    infoRight: {
      top: "Explore the scenes of Beautiful mountains",
      bot: "and their serenity.",
    },
    images: [
      "./images/1.jpg",
      undefined,
      "./images/2.jpg",
      undefined,
      "./images/3.jpg",
      "./images/4.jpg",
      "./images/5.jpg",
      undefined,
      "./images/6.jpg",
      "./images/7.jpg",
    ],
  },
  {
    id: 18,
    title: "first",
    bgColor: { r: 156, g: 168, b: 182 },
    color: { r: 41, g: 32, b: 26 },
    topTitle: "Autumn",
    botTitle: "Silence",
    infoLeft: {
      a: ["Completed", "March 2023"],
      b: ["Type", "Promotional"],
      c: ["Role", "Frontend Dev"],
      d: ["Client", "MGM Studios - Watson DC"],
    },
    infoRight: {
      top: "Explore the scenes of Beautiful mountains",
      bot: "and their serenity.",
    },
    images: [
      "./images/1.jpg",
      undefined,
      "./images/2.jpg",
      "./images/3.jpg",
      "./images/4.jpg",
      undefined,
      "./images/5.jpg",
      "./images/6.jpg",
      undefined,
      "./images/7.jpg",
    ],
  },

  {
    id: 19,
    title: "first",
    bgColor: { r: 144, g: 151, b: 152 },
    color: { r: 205, g: 197, b: 187 },
    topTitle: "Autumn",
    botTitle: "Silence",
    infoLeft: {
      a: ["Completed", "March 2023"],
      b: ["Type", "Promotional"],
      c: ["Role", "Frontend Dev"],
      d: ["Client", "MGM Studios - Watson DC"],
    },
    infoRight: {
      top: "Explore the scenes of Beautiful mountains",
      bot: "and their serenity.",
    },
    images: [
      "./images/1.jpg",
      undefined,
      "./images/2.jpg",
      undefined,
      "./images/3.jpg",
      "./images/4.jpg",
      "./images/5.jpg",
      "./images/6.jpg",
      undefined,
      "./images/7.jpg",
    ],
  },
  {
    id: 20,
    title: "first",
    bgColor: { r: 183, g: 202, b: 203 },
    color: { r: 176, g: 65, b: 19 },
    topTitle: "Autumn",
    botTitle: "Silence",
    infoLeft: {
      a: ["Completed", "March 2023"],
      b: ["Type", "Promotional"],
      c: ["Role", "Frontend Dev"],
      d: ["Client", "MGM Studios - Watson DC"],
    },
    infoRight: {
      top: "Explore the scenes of Beautiful mountains",
      bot: "and their serenity.",
    },
    images: [
      "./images/1.jpg",
      undefined,
      "./images/2.jpg",
      "./images/3.jpg",
      "./images/4.jpg",
      "./images/5.jpg",
      undefined,
      "./images/6.jpg",
      undefined,
      "./images/7.jpg",
    ],
  },
  {
    id: 21,
    title: "first",
    bgColor: { r: 65, g: 51, b: 40 },
    color: { r: 166, g: 189, b: 88 },
    topTitle: "Autumn",
    botTitle: "Silence",
    infoLeft: {
      a: ["Completed", "March 2023"],
      b: ["Type", "Promotional"],
      c: ["Role", "Frontend Dev"],
      d: ["Client", "MGM Studios - Watson DC"],
    },
    infoRight: {
      top: "Explore the scenes of Beautiful mountains",
      bot: "and their serenity.",
    },
    images: [
      "./images/1.jpg",
      undefined,
      "./images/2.jpg",
      "./images/3.jpg",
      "./images/4.jpg",
      "./images/5.jpg",
      undefined,
      "./images/6.jpg",
      undefined,
      "./images/7.jpg",
    ],
  },
  {
    id: 22,
    title: "first",
    bgColor: { r: 241, g: 229, b: 171 },
    color: { r: 65, g: 70, b: 64 },
    topTitle: "Autumn",
    botTitle: "Silence",
    infoLeft: {
      a: ["Completed", "March 2023"],
      b: ["Type", "Promotional"],
      c: ["Role", "Frontend Dev"],
      d: ["Client", "MGM Studios - Watson DC"],
    },
    infoRight: {
      top: "Explore the scenes of Beautiful mountains",
      bot: "and their serenity.",
    },
    images: [
      undefined,
      "./images/1.jpg",
      "./images/2.jpg",
      "./images/3.jpg",
      undefined,
      "./images/4.jpg",
      "./images/5.jpg",
      "./images/6.jpg",
      "./images/7.jpg",
      undefined,
    ],
  },
  {
    id: 23,
    title: "first",
    bgColor: { r: 68, g: 64, b: 53 },
    color: { r: 225, g: 211, b: 190 },
    topTitle: "Autumn",
    botTitle: "Silence",
    infoLeft: {
      a: ["Completed", "March 2023"],
      b: ["Type", "Promotional"],
      c: ["Role", "Frontend Dev"],
      d: ["Client", "MGM Studios - Watson DC"],
    },
    infoRight: {
      top: "Explore the scenes of Beautiful mountains",
      bot: "and their serenity.",
    },
    images: [
      "./images/1.jpg",
      "./images/2.jpg",
      undefined,
      "./images/3.jpg",
      "./images/4.jpg",
      undefined,
      "./images/5.jpg",
      "./images/6.jpg",
      undefined,
      "./images/7.jpg",
    ],
  },
  {
    id: 24,
    title: "first",
    bgColor: { r: 225, g: 184, b: 163 },
    color: { r: 250, g: 254, b: 255 },
    topTitle: "Autumn",
    botTitle: "Silence",
    infoLeft: {
      a: ["Completed", "March 2023"],
      b: ["Type", "Promotional"],
      c: ["Role", "Frontend Dev"],
      d: ["Client", "MGM Studios - Watson DC"],
    },
    infoRight: {
      top: "Explore the scenes of Beautiful mountains",
      bot: "and their serenity.",
    },
    images: [
      "./images/1.jpg",
      "./images/2.jpg",
      "./images/3.jpg",
      undefined,
      "./images/4.jpg",
      undefined,
      "./images/5.jpg",
      "./images/6.jpg",
      undefined,
      "./images/7.jpg",
    ],
  },
  {
    id: 25,
    title: "first",
    bgColor: { r: 17, g: 11, b: 7 },
    color: { r: 223, g: 150, b: 63 },
    topTitle: "Autumn",
    botTitle: "Silence",
    infoLeft: {
      a: ["Completed", "March 2023"],
      b: ["Type", "Promotional"],
      c: ["Role", "Frontend Dev"],
      d: ["Client", "MGM Studios - Watson DC"],
    },
    infoRight: {
      top: "Explore the scenes of Beautiful mountains",
      bot: "and their serenity.",
    },
    images: [
      "./images/1.jpg",
      undefined,
      "./images/2.jpg",
      "./images/3.jpg",
      undefined,
      "./images/4.jpg",
      undefined,
      "./images/5.jpg",
      "./images/6.jpg",
      "./images/7.jpg",
    ],
  },
  {
    id: 26,
    title: "first",
    bgColor: { r: 253, g: 253, b: 253 },
    color: { r: 83, g: 70, b: 38 },
    topTitle: "Autumn",
    botTitle: "Silence",
    infoLeft: {
      a: ["Completed", "March 2023"],
      b: ["Type", "Promotional"],
      c: ["Role", "Frontend Dev"],
      d: ["Client", "MGM Studios - Watson DC"],
    },
    infoRight: {
      top: "Explore the scenes of Beautiful mountains",
      bot: "and their serenity.",
    },
    images: [
      "./images/1.jpg",
      undefined,
      "./images/2.jpg",
      "./images/3.jpg",
      "./images/4.jpg",
      undefined,
      "./images/5.jpg",
      "./images/6.jpg",
      undefined,
      "./images/7.jpg",
    ],
  },
  {
    id: 27,
    title: "first",
    bgColor: { r: 51, g: 51, b: 51 },
    color: { r: 255, g: 255, b: 255 },
    topTitle: "Autumn",
    botTitle: "Silence",
    infoLeft: {
      a: ["Completed", "March 2023"],
      b: ["Type", "Promotional"],
      c: ["Role", "Frontend Dev"],
      d: ["Client", "MGM Studios - Watson DC"],
    },
    infoRight: {
      top: "Explore the scenes of Beautiful mountains",
      bot: "and their serenity.",
    },
    images: [
      "./images/1.jpg",
      undefined,
      "./images/2.jpg",
      undefined,
      "./images/3.jpg",
      "./images/4.jpg",
      "./images/5.jpg",
      undefined,
      "./images/6.jpg",
      "./images/7.jpg",
    ],
  },
  {
    id: 28,
    title: "first",
    bgColor: { r: 228, g: 212, b: 187 },
    color: { r: 81, g: 120, b: 221 },
    topTitle: "Autumn",
    botTitle: "Silence",
    infoLeft: {
      a: ["Completed", "March 2023"],
      b: ["Type", "Promotional"],
      c: ["Role", "Frontend Dev"],
      d: ["Client", "MGM Studios - Watson DC"],
    },
    infoRight: {
      top: "Explore the scenes of Beautiful mountains",
      bot: "and their serenity.",
    },
    images: [
      "./images/1.jpg",
      undefined,
      "./images/2.jpg",
      "./images/3.jpg",
      "./images/4.jpg",
      undefined,
      "./images/5.jpg",
      "./images/6.jpg",
      undefined,
      "./images/7.jpg",
    ],
  },
  {
    id: 29,
    title: "first",
    bgColor: { r: 196, g: 199, b: 205 },
    color: { r: 117, g: 79, b: 57 },
    topTitle: "Spring",
    botTitle: "Silence",
    infoLeft: {
      a: ["Completed", "March 2023"],
      b: ["Type", "Promotional"],
      c: ["Role", "Frontend Dev"],
      d: ["Client", "MGM Studios - Watson DC"],
    },
    infoRight: {
      top: "Explore the scenes of Beautiful mountains",
      bot: "and their serenity.",
    },
    images: [
      "./images/1.jpg",
      undefined,
      "./images/2.jpg",
      "./images/3.jpg",
      "./images/4.jpg",
      undefined,
      "./images/5.jpg",
      "./images/6.jpg",
      undefined,
      "./images/7.jpg",
    ],
  },
];
