export const data = [
  {
    id: 0,
    title: "first",
    hidden: [1, 5, 7],
    images: [
      "./images/1.png",
      undefined,
      "./images/2.png",
      "./images/3.png",
      undefined,
      "./images/4.png",
      undefined,
      "./images/5.png",
      "./images/6.png",
      "./images/7.png",
    ],
  },
  {
    id: 0,
    title: "first",
    hidden: [1, 5, 7],
    images: [
      "./images/1.png",
      "./images/2.png",
      undefined,
      "./images/3.png",
      "./images/4.png",
      undefined,
      "./images/5.png",
      undefined,
      "./images/6.png",
      "./images/7.png",
    ],
  },
  {
    id: 0,
    title: "first",
    hidden: [1, 5, 7],
    images: [
      "./images/1.png",
      "./images/1.png",
      "./images/1.png",
      undefined,
      "./images/1.png",
      undefined,
      "./images/1.png",
      "./images/1.png",
      undefined,
      "./images/1.png",
    ],
  },
  {
    id: 0,
    title: "first",
    hidden: [1, 5, 7],
    images: [
      "./images/1.png",
      undefined,
      "./images/1.png",
      "./images/1.png",
      undefined,
      "./images/1.png",
      "./images/1.png",
      "./images/1.png",
      undefined,
      "./images/1.png",
    ],
  },
  {
    id: 0,
    title: "first",
    hidden: [1, 5, 7],
    images: [
      "./images/1.png",
      undefined,
      "./images/1.png",
      "./images/1.png",
      undefined,
      undefined,
      "./images/1.png",
      "./images/1.png",
      undefined,
      "./images/1.png",
    ],
  },
  {
    id: 0,
    title: "first",
    hidden: [1, 5, 7],
    images: [
      undefined,
      "./images/1.png",
      "./images/1.png",
      undefined,
      "./images/1.png",
      "./images/1.png",
      undefined,
      "./images/1.png",
      "./images/1.png",
      undefined,
    ],
  },
  {
    id: 0,
    title: "first",
    hidden: [1, 5, 7],
    images: [
      undefined,
      undefined,
      "./images/1.png",
      "./images/1.png",
      "./images/1.png",
      "./images/1.png",
      "./images/1.png",
      "./images/1.png",
      undefined,
      undefined,
    ],
  },
  {
    id: 0,
    title: "first",
    hidden: [1, 5, 7],
    images: [
      undefined,
      "./images/1.png",
      "./images/1.png",
      undefined,
      "./images/1.png",
      "./images/1.png",
      undefined,
      "./images/1.png",
      "./images/1.png",
      undefined,
    ],
  },
];
