export const data = [
  {
    id: 0,
    title: "first",
    hidden: [1, 5, 7],
    images: [
      "./images/1.png",
      undefined,
      "./images/2.png",
      "./images/3.png",
      undefined,
      "./images/4.png",
      undefined,
      "./images/5.png",
      "./images/6.png",
      "./images/7.png",
    ],
  },
  {
    id: 1,
    title: "first",
    hidden: [1, 5, 7],
    images: [
      "./images/1.png",
      "./images/2.png",
      undefined,
      "./images/3.png",
      "./images/4.png",
      undefined,
      "./images/5.png",
      undefined,
      "./images/6.png",
      "./images/7.png",
    ],
  },
  {
    id: 2,
    title: "first",
    hidden: [1, 5, 7],
    images: [
      "./images/1.png",
      "./images/1.png",
      "./images/1.png",
      undefined,
      "./images/1.png",
      undefined,
      "./images/1.png",
      "./images/1.png",
      undefined,
      "./images/1.png",
    ],
  },
  {
    id: 3,
    title: "first",
    hidden: [1, 5, 7],
    images: [
      "./images/1.png",
      undefined,
      "./images/1.png",
      "./images/1.png",
      undefined,
      "./images/1.png",
      "./images/1.png",
      "./images/1.png",
      undefined,
      "./images/1.png",
    ],
  },
  {
    id: 4,
    title: "first",
    hidden: [1, 5, 7],
    images: [
      "./images/1.png",
      undefined,
      "./images/1.png",
      "./images/1.png",
      undefined,
      undefined,
      "./images/1.png",
      "./images/1.png",
      undefined,
      "./images/1.png",
    ],
  },
  {
    id: 5,
    title: "first",
    hidden: [1, 5, 7],
    images: [
      undefined,
      "./images/1.png",
      "./images/1.png",
      undefined,
      "./images/1.png",
      "./images/1.png",
      undefined,
      "./images/1.png",
      "./images/1.png",
      undefined,
    ],
  },
  {
    id: 6,
    title: "first",
    hidden: [1, 5, 7],
    images: [
      undefined,
      undefined,
      "./images/1.png",
      "./images/1.png",
      "./images/1.png",
      "./images/1.png",
      "./images/1.png",
      "./images/1.png",
      undefined,
      undefined,
    ],
  },
  {
    id: 7,
    title: "first",
    hidden: [1, 5, 7],
    images: [
      undefined,
      "./images/1.png",
      "./images/1.png",
      undefined,
      "./images/1.png",
      "./images/1.png",
      undefined,
      "./images/1.png",
      "./images/1.png",
      undefined,
    ],
  },
  {
    id: 8,
    title: "first",
    hidden: [1, 5, 7],
    images: [
      undefined,
      "./images/1.png",
      "./images/1.png",
      undefined,
      "./images/1.png",
      "./images/1.png",
      undefined,
      "./images/1.png",
      "./images/1.png",
      undefined,
    ],
  },
  {
    id: 9,
    title: "first",
    hidden: [1, 5, 7],
    images: [
      undefined,
      "./images/1.png",
      "./images/1.png",
      undefined,
      "./images/1.png",
      "./images/1.png",
      undefined,
      "./images/1.png",
      "./images/1.png",
      undefined,
    ],
  },

  {
    id: 10,
    title: "first",
    hidden: [1, 5, 7],
    images: [
      "./images/1.png",
      undefined,
      "./images/2.png",
      "./images/3.png",
      undefined,
      "./images/4.png",
      undefined,
      "./images/5.png",
      "./images/6.png",
      "./images/7.png",
    ],
  },
  {
    id: 11,
    title: "first",
    hidden: [1, 5, 7],
    images: [
      "./images/1.png",
      "./images/2.png",
      undefined,
      "./images/3.png",
      "./images/4.png",
      undefined,
      "./images/5.png",
      undefined,
      "./images/6.png",
      "./images/7.png",
    ],
  },
  {
    id: 12,
    title: "first",
    hidden: [1, 5, 7],
    images: [
      "./images/1.png",
      "./images/1.png",
      "./images/1.png",
      undefined,
      "./images/1.png",
      undefined,
      "./images/1.png",
      "./images/1.png",
      undefined,
      "./images/1.png",
    ],
  },
  {
    id: 13,
    title: "first",
    hidden: [1, 5, 7],
    images: [
      "./images/1.png",
      undefined,
      "./images/1.png",
      "./images/1.png",
      undefined,
      "./images/1.png",
      "./images/1.png",
      "./images/1.png",
      undefined,
      "./images/1.png",
    ],
  },
  {
    id: 14,
    title: "first",
    hidden: [1, 5, 7],
    images: [
      "./images/1.png",
      undefined,
      "./images/1.png",
      "./images/1.png",
      undefined,
      undefined,
      "./images/1.png",
      "./images/1.png",
      undefined,
      "./images/1.png",
    ],
  },
  {
    id: 15,
    title: "first",
    hidden: [1, 5, 7],
    images: [
      undefined,
      "./images/1.png",
      "./images/1.png",
      undefined,
      "./images/1.png",
      "./images/1.png",
      undefined,
      "./images/1.png",
      "./images/1.png",
      undefined,
    ],
  },
  {
    id: 16,
    title: "first",
    hidden: [1, 5, 7],
    images: [
      undefined,
      undefined,
      "./images/1.png",
      "./images/1.png",
      "./images/1.png",
      "./images/1.png",
      "./images/1.png",
      "./images/1.png",
      undefined,
      undefined,
    ],
  },
  {
    id: 17,
    title: "first",
    hidden: [1, 5, 7],
    images: [
      undefined,
      "./images/1.png",
      "./images/1.png",
      undefined,
      "./images/1.png",
      "./images/1.png",
      undefined,
      "./images/1.png",
      "./images/1.png",
      undefined,
    ],
  },
  {
    id: 18,
    title: "first",
    hidden: [1, 5, 7],
    images: [
      undefined,
      "./images/1.png",
      "./images/1.png",
      undefined,
      "./images/1.png",
      "./images/1.png",
      undefined,
      "./images/1.png",
      "./images/1.png",
      undefined,
    ],
  },
  {
    id: 19,
    title: "first",
    hidden: [1, 5, 7],
    images: [
      undefined,
      "./images/1.png",
      "./images/1.png",
      undefined,
      "./images/1.png",
      "./images/1.png",
      undefined,
      "./images/1.png",
      "./images/1.png",
      undefined,
    ],
  },

  {
    id: 20,
    title: "first",
    hidden: [1, 5, 7],
    images: [
      "./images/1.png",
      undefined,
      "./images/2.png",
      "./images/3.png",
      undefined,
      "./images/4.png",
      undefined,
      "./images/5.png",
      "./images/6.png",
      "./images/7.png",
    ],
  },
  {
    id: 21,
    title: "first",
    hidden: [1, 5, 7],
    images: [
      "./images/1.png",
      "./images/2.png",
      undefined,
      "./images/3.png",
      "./images/4.png",
      undefined,
      "./images/5.png",
      undefined,
      "./images/6.png",
      "./images/7.png",
    ],
  },
  {
    id: 22,
    title: "first",
    hidden: [1, 5, 7],
    images: [
      "./images/1.png",
      "./images/1.png",
      "./images/1.png",
      undefined,
      "./images/1.png",
      undefined,
      "./images/1.png",
      "./images/1.png",
      undefined,
      "./images/1.png",
    ],
  },
  {
    id: 23,
    title: "first",
    hidden: [1, 5, 7],
    images: [
      "./images/1.png",
      undefined,
      "./images/1.png",
      "./images/1.png",
      undefined,
      "./images/1.png",
      "./images/1.png",
      "./images/1.png",
      undefined,
      "./images/1.png",
    ],
  },
  {
    id: 24,
    title: "first",
    hidden: [1, 5, 7],
    images: [
      "./images/1.png",
      undefined,
      "./images/1.png",
      "./images/1.png",
      undefined,
      undefined,
      "./images/1.png",
      "./images/1.png",
      undefined,
      "./images/1.png",
    ],
  },
  {
    id: 25,
    title: "first",
    hidden: [1, 5, 7],
    images: [
      undefined,
      "./images/1.png",
      "./images/1.png",
      undefined,
      "./images/1.png",
      "./images/1.png",
      undefined,
      "./images/1.png",
      "./images/1.png",
      undefined,
    ],
  },
  {
    id: 26,
    title: "first",
    hidden: [1, 5, 7],
    images: [
      undefined,
      undefined,
      "./images/1.png",
      "./images/1.png",
      "./images/1.png",
      "./images/1.png",
      "./images/1.png",
      "./images/1.png",
      undefined,
      undefined,
    ],
  },
  {
    id: 27,
    title: "first",
    hidden: [1, 5, 7],
    images: [
      undefined,
      "./images/1.png",
      "./images/1.png",
      undefined,
      "./images/1.png",
      "./images/1.png",
      undefined,
      "./images/1.png",
      "./images/1.png",
      undefined,
    ],
  },
  {
    id: 28,
    title: "first",
    hidden: [1, 5, 7],
    images: [
      undefined,
      "./images/1.png",
      "./images/1.png",
      undefined,
      "./images/1.png",
      "./images/1.png",
      undefined,
      "./images/1.png",
      "./images/1.png",
      undefined,
    ],
  },
  {
    id: 29,
    title: "first",
    hidden: [1, 5, 7],
    images: [
      undefined,
      "./images/1.png",
      "./images/1.png",
      undefined,
      "./images/1.png",
      "./images/1.png",
      undefined,
      "./images/1.png",
      "./images/1.png",
      undefined,
    ],
  },
];
